package com.asmdev.api.pos.utils.status;

public enum NamePermissions {
    AUTH_LOGIN,
    AUTH_LOGOUT,
    AUTH_ME,

    USER_LIST,
    USER_GET,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,
    USER_RESTORE,

    ROLE_LIST,
    ROLE_GET,
    ROLE_CREATE,
    ROLE_UPDATE,
    ROLE_DELETE,
    ROLE_RESTORE,

    PERMISSION_LIST,
    PERMISSION_GET,
    PERMISSION_ASSIGN_TO_ROLE,

    CUSTOMER_LIST,
    CUSTOMER_GET,
    CUSTOMER_CREATE,
    CUSTOMER_UPDATE,
    CUSTOMER_DELETE,
    CUSTOMER_RESTORE,


    SUPPLIER_LIST,
    SUPPLIER_GET,
    SUPPLIER_CREATE,
    SUPPLIER_UPDATE,
    SUPPLIER_DELETE,
    SUPPLIER_RESTORE,

    CATEGORY_LIST,
    CATEGORY_GET,
    CATEGORY_CREATE,
    CATEGORY_UPDATE,
    CATEGORY_DELETE,
    CATEGORY_RESTORE,

    PRODUCT_LIST,
    PRODUCT_GET,
    PRODUCT_CREATE,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,
    PRODUCT_RESTORE,
    PRODUCT_IMPORT,
    PRODUCT_EXPORT,

    PURCHASE_LIST,
    PURCHASE_GET,
    PURCHASE_CREATE,
    PURCHASE_CANCEL,
    PURCHASE_DELETE,
    PURCHASE_RESTORE,

    SALE_LIST,
    SALE_GET,
    SALE_CREATE,
    SALE_CANCEL,
    SALE_DELETE,
    SALE_RESTORE,

    INVENTORY_MOVEMENT_LIST,
    INVENTORY_MOVEMENT_CREATE,

    SETTING_CREATE,
    SETTING_LIST,
    SETTING_GET,
    SETTING_UPDATE,

    REPORT_SALES_BY_DATE,
    REPORT_TOP_PRODUCTS,
    REPORT_TOP_CLIENTS,
    REPORT_INVENTORY_LOW_STOCK,
    REPORT_PROFIT_ESTIMATE,
    REPORT_SALES_EXPORT,
    REPORT_PURCHASES_EXPORT,
    REPORT_INVENTORY_EXPORT,
    REPORT_FULL_EXPORT,

    AUDIT_LOG_LIST,
    AUDIT_LOG_GET,













    }
