package com.asmdev.api.pos.utils.status;

public enum NamePermissions {
    AUTH_LOGIN,
    AUTH_LOGOUT,
    AUTH_ME,

    CASH_MOVEMENT_LIST,
    CASH_MOVEMENT_GET,
    CASH_MOVEMENT_CREATE,
    CASH_MOVEMENT_UPDATE,
    CASH_MOVEMENT_CANCELED,
    CASH_MOVEMENT_EXPORT,

    CASH_REGISTER_LIST,
    CASH_REGISTER_GET,
    CASH_REGISTER_CREATE,
    CASH_REGISTER_UPDATE,
    CASH_REGISTER_CLOSED,
    CASH_REGISTER_EXPORT,

    CATEGORY_LIST,
    CATEGORY_GET,
    CATEGORY_CREATE,
    CATEGORY_UPDATE,
    CATEGORY_DELETE,
    CATEGORY_IMPORT,
    CATEGORY_EXPORT,

    CUSTOMER_LIST,
    CUSTOMER_GET,
    CUSTOMER_CREATE,
    CUSTOMER_UPDATE,
    CUSTOMER_DELETE,
    CUSTOMER_RESTORE,
    CUSTOMER_EXPORT,

    INVENTORY_MOVEMENT_LIST,
    INVENTORY_MOVEMENT_GET,
    INVENTORY_MOVEMENT_CREATE,
    INVENTORY_MOVEMENT_CANCELED,
    INVENTORY_MOVEMENT_EXPORT,

    PERMISSION_LIST,
    PERMISSION_GET,
    PERMISSION_CREATE,
    PERMISSION_UPDATE,
    PERMISSION_CANCELED,
    PERMISSION_IMPORT,
    PERMISSION_EXPORT,


    PRODUCT_LIST,
    PRODUCT_GET,
    PRODUCT_GET_LOW_STOCK,
    PRODUCT_CREATE,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,
    PRODUCT_IMPORT,
    PRODUCT_EXPORT,

    PURCHASE_LIST,
    PURCHASE_GET,
    PURCHASE_CREATE,
    PURCHASE_CANCELED,
    PURCHASE_EXPORT,

    ROLE_LIST,
    ROLE_GET,
    ROLE_CREATE,
    ROLE_UPDATE,
    ROLE_DELETE,
    ROLE_EXPORT,

    SALE_LIST,
    SALE_GET,
    SALE_CREATE,
    SALE_CANCELED,
    SALE_EXPORT,


    SUPPLIER_LIST,
    SUPPLIER_GET,
    SUPPLIER_CREATE,
    SUPPLIER_UPDATE,
    SUPPLIER_DELETE,
    SUPPLIER_IMPORT,
    SUPPLIER_EXPORT,

    USER_LIST,
    USER_GET,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,
    USER_EXPORT,


    SETTING_CREATE,
    SETTING_LIST,
    SETTING_GET,
    SETTING_UPDATE,

    REPORT_SALES_BY_DATE,
    REPORT_TOP_PRODUCTS,
    REPORT_TOP_CLIENTS,
    REPORT_INVENTORY_LOW_STOCK,
    REPORT_PROFIT_ESTIMATE,
    REPORT_SALES_EXPORT,
    REPORT_PURCHASES_EXPORT,
    REPORT_INVENTORY_EXPORT,
    REPORT_FULL_EXPORT,

    AUDIT_LOG_LIST,
    AUDIT_LOG_GET,













    }
